name: cubetiq
description: CUBETIQ Dart Shared is functions, utils, and extensions for developers.
version: 1.0.1
homepage: https://www.cubetiqs.com
repository: https://git.cubetiqs.com/CUBETIQ/cubetiq_dart_shared.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
